### ISSUE TITLE
Can't find argptr() in xv6. 

### ISSUE THREAD

**Issue by Patchwork53** [Tahmid04/xv6-scheduling-july-2022#1]
I found argaddr() in system call fstat() though which seems to pass pointers from user to kernel.

**Comment by Tahmid04** [comment]
Thanks for noticing. It seems `argptr()` has been deprecated and `argaddr()` is being used in lieu of it. Please refer to `syscall.c` for its implementation and `sysfile.c` or `sysproc.c` for more usage.
