### ISSUE TITLE
"init" process never uses its ticket

### ISSUE THREAD

**Issue by showvikbiswas** [Tahmid04/xv6-scheduling-july-2022#2]
Dear Sir

As part of our assignment, we were asked to give processes a default ticket value of 1. I have assumed this includes **init**, the very first process, and have assigned a ticket value of 1 to it. However, once **init** forks **sh**, **init** is always in the **sleep** state (as seen by **procdump**), and never ticks again for as long as xv6 runs. If it does not ever run again, it will never use its ticket. 

We were asked to reinstate ticket values **only** when **all** processes have zero tickets. How do we deal with this apparent contradiction? Or have I missed anything?

Thanks in advance
Showvik
1805068

**Comment by PatchworkProgrammer** [comment]
I think we are only meant to consider RUNNABLE processes when calculating ticket sums.

**Comment by Tahmid04** [comment]
Sorry for replying late. When scheduling processes, we only consider `RUNNABLE` processes. So, while calculating probabilities or updating ticket counts, you need not consider any processes having other states. 

I have updated the specification accordingly to clear the ambiguity. Hope that helps.

**Comment by Tahmid04** [comment]
Since there has not been any recent activity, I am closing this issue. Feel free to reopen.
