### ISSUE TITLE
Ticket assignment during fork()

### ISSUE THREAD

**Issue by TokiTahmid64** [Tahmid04/xv6-scheduling-july-2022#3]
Sir we are instructed to pass the parent's ticket number to child's ticket number when fork() called, should it be the parent's Initial ticket number, or the Current ticket number? Its not clearly mentioned in the specs.

Thanks

Md Toki Tahmid
1805030

**Comment by Tahmid04** [comment]
It should be the original ticket count. I have updated the specification accordingly. Thanks.

**Comment by Tahmid04** [comment]
Since there has not been any recent activity, I am closing this issue. Feel free to reopen.
