### ISSUE TITLE
Process Selection for probability calculation

### ISSUE THREAD

**Issue by parthokunda** [Tahmid04/xv6-scheduling-july-2022#4]
Sir, should we consider all process having a ticket or only the runnable ones during probability calculation?

![image](https://user-images.githubusercontent.com/76593389/212526323-295acb70-69fd-4773-9578-cfa14e370172.png)

**Comment by Tahmid04** [comment]
Check [this issue](https://github.com/Tahmid04/xv6-scheduling-july-2022/issues/2).
