### ISSUE TITLE
Should the shell process have a high ticket_original by default?

### ISSUE THREAD

**Issue by Patchwork53** [Tahmid04/xv6-scheduling-july-2022#5]
If I have multiple `testticket` processes with a moderately high number of tickets (~10), it takes a long time for the shell process to be be selected by the scheduler. So there's a significant waiting time in between when I can input shell commands. I believe its because shell has a default ticket count of 1, although there could be something wrong in my implementation. Please advise.

Also, my implementation of `testticket` contains an infinite loop at the end so if I run something like:
 `testticket 5 &; testticket 4 &; testticket 3`

The very last process `testticket 3` continues running and doesn't return to shell. A possible workaround is having a redundant call at the end like:
 `testticket 5 &; testticket 4 &; testticket 3 &; echo 1`
Will this be acceptable?

**Comment by Tahmid04** [comment]
These are implementation-specific design choices. We are leaving them open for you.

**Comment by MJKSabit** [comment]
Writing this will take you to shell and will not wait for the last process to end -
`testticket 5 &; testticket 4 &; testticket 3 &;`
